export interface IEscola {
  nome: string;
  etapas: string[];
  turmas: string[];
}

export const escolas: IEscola[] = [
  {
    nome: 'Escola São Francisco',
    etapas: ['1º ano', '2º ano', '3º ano', '4º ano', '5º ano'],
    turmas: [
      '1º ano A',
      '2º ano A',
      '3º ano A',
      '4º ano A',
      '5º ano A',
      '1º ano B',
      '2º ano B',
      '3º ano B',
      '4º ano B',
      '5º ano B',
      '1º ano C',
      '2º ano C',
      '3º ano C',
      '4º ano C',
      '5º ano C',
    ],
  },
  {
    nome: 'Escola Rio das Pedras',
    etapas: ['6º ano', '7º ano', '8º ano', '9º ano'],
    turmas: [
      '6º ano A',
      '7º ano A',
      '8º ano A',
      '9º ano A',
      '6º ano B',
      '7º ano B',
      '8º ano B',
      '9º ano B',
      '6º ano C',
      '7º ano C',
      '8º ano C',
      '9º ano C',
    ],
  },
  {
    nome: 'Escola Municipal Santa Mônica',
    etapas: [
      '1º ano',
      '2º ano',
      '3º ano',
      '4º ano',
      '5º ano',
      '6º ano',
      '7º ano',
      '8º ano',
      '9º ano',
    ],
    turmas: [
      '1º ano A',
      '2º ano A',
      '3º ano A',
      '4º ano A',
      '5º ano A',
      '1º ano B',
      '2º ano B',
      '3º ano B',
      '4º ano B',
      '5º ano B',
      '1º ano C',
      '2º ano C',
      '3º ano C',
      '4º ano C',
      '5º ano C',
      '6º ano A',
      '7º ano A',
      '8º ano A',
      '9º ano A',
      '6º ano B',
      '7º ano B',
      '8º ano B',
      '9º ano B',
      '6º ano C',
      '7º ano C',
      '8º ano C',
      '9º ano C',
    ],
  },
];
